### PR TITLE
Change routes, fix visual bugs, changed drawer

### LINKED ISSUE #36: Connect Organization page to Core
## Routes:
* __GET__ ___/organizations/:organization_id___ - returns data about organization by id
* __DELETE__ ___/organizations/:organization_id___ - delete organization.
* __GET__ ___/organizations/:organization_id/users___ - get an array of all organization users.
* __DELETE__ ___/organizations/:organization_id/users___  
__body__: {_userId_: ___number___} - delete user from organization
* __POST__ ___/organizations/:organization_id/users___  
__body__: {_userId_: ___number___} - add user to organization

### LINKED ISSUE #56: Create entity for Organization
Create entity with validators.

### LINKED ISSUE #57: Create entity for User Tokens
Create entity with validation

### LINKED ISSUE #65: Fix bug with header
Need to fix incorrect display of header when switched to mobile version, if side bar menu is opened
image

### LINKED ISSUE #66: Fix bug with TasksTable in RenderJobDetailsPage

### LINKED ISSUE #67: make paddings much smaller for mobile version
I guess such paddings are created due to incorrect work of side bar menu.
image

### LINKED ISSUE #68: Fix warnings and erros in console

### LINKED ISSUE #69: Change routes system

### LINKED ISSUE #70: Add Logout button in Header

### PR DESCRIPTION
**Pull request by ZaykaNya**

### CODE REVIEW

File: src/interfaces/Token.ts [hunk 1]
```diff
@@ -1,15 +1,16 @@
...
+ * File last modified: 16.10.2020, 1:33
  * All rights reserved.
  */
 
-export default interface Token {
-    id: number;
-    name: string;
-    description: string;
-    createdAt: Date;
+export default interface Token{
```
Comment (DanilAndreev) [inline src/interfaces/Token.ts:16]: JSDoc

File: src/views/AuthorizationPageView/AuthorizationPageView.tsx [hunk 2]
```diff
@@ -87,69 +88,75 @@ const AuthorizationPageView = React.forwardRef((props: AuthorizationPageViewProp
...
-                    </Grid>
-                    <Grid item>
-                        <Link href="#" variant="body2">
-                            {"Don't have an account? Sign Up"}
-                        </Link>
-                    </Grid>
-                </Grid>
-            </Box>
+        <Switch>
+            <Route exact path={path}>
```
Comment (DanilAndreev) [inline src/views/AuthorizationPageView/AuthorizationPageView.tsx]: Remove ```<Switch/>``` and ```<Route/>```. Switch with just one route - it's powerful!

File: src/views/SignUpPage/SignUpPage.tsx [hunk 3]
```diff
@@ -78,78 +78,85 @@ const SignUpPage = React.forwardRef((props: SignUpPageProps, ref: Ref<any>) => {
...
-                            name="email"
-                            autoComplete="email"
-                            onChange={handleInput}
-                        />
-                    </Grid>
-                    <Grid item xs={12}>
-                        <TextField
-                            variant="outlined"
-                            required
+        <Switch>
```
Comment (DanilAndreev) [inline src/views/SignUpPage/SignUpPage.tsx]: Remove ```<Switch/>``` and ```<Route/>```

File: src/views/SubmitPageView/SubmitPageView.tsx [hunk 4]
```diff
@@ -204,53 +204,59 @@ const SubmitPageView = React.forwardRef((props: SubmitPagePropsStyled, ref: Ref<
...
-                                primary={<Typography variant="h6">Render settings</Typography>}
-                            />
-                            {/*<ListItemSecondaryAction>*/}
-                            {/*    <IconButton><AddIcon/></IconButton>*/}
-                            {/*</ListItemSecondaryAction>*/}
-                        </ListItem>
-                    </List>
-                </Grid>
-                {renderSettings}
+        <Switch>
```
Comment (DanilAndreev) [inline src/views/SubmitPageView/SubmitPageView.tsx]: Extra ```<Switch/>``` and ```<Route/>```

File: src/views/UserPageView/LocalComponents/TokensViewer/styles.ts [hunk 5]
```diff
@@ -19,13 +20,70 @@ const styles = (theme: Theme) => createStyles({
...
+    },
+    createTokenControls:{
+        display:"flex",
+        justifyContent:"flex-end",
+        alignItems:"center",
+    },
+    wrapWord: {
+        // whiteSpace: "-moz-pre-wrap",  /* Mozilla, since 1999 */
+        whiteSpace: "pre-wrap",          /* Chrome & Safari */
+        // whiteSpace: "-pre-wrap",                 /* Opera 4-6 */
```
Comment (DanilAndreev) [inline src/views/UserPageView/LocalComponents/TokensViewer/styles.ts]: Remove extra styles.

**Review by DanilAndreev — CHANGES_REQUESTED** [review]

**Review by DanilAndreev — APPROVED** [review]
