### PR TITLE
Connected users and organizations to Core and change Monitor Layout

### LINKED ISSUE #6: Create Main Pathfinder layout
Create basic Pathfinder Monitor layout with menu, header and other basic things.

### LINKED ISSUE #50: Fix incorrect add button on Submit Job page
## Overview
Make __Add__ buttom in __Submit Page__ in ___Material Design__ style. For example, make it fullwidth in mobile version.
## Images
image

### LINKED ISSUE #58: Connect User Tokens to Core
## Routes
* __GET__ ___/tokens___ get array of all tokens.
* __DELETE__ ___/tokens/:id___ delete token with selected id.
* __POST__ ___/token___ create new token. Body: 
```
{
  name: string,
  description: string
}
```

### LINKED ISSUE #59: Connect organizations on User Page to Core
## Route

* __GET__ ___/users/:id___ get user by id

### LINKED ISSUE #60: Connect users on Organization Page to Core
## Route
* __GET__ ___/organizations/:organization_id___ returns data about organization by id

### PR DESCRIPTION
**Pull request by ZaykaNya**

### CODE REVIEW

File: src/entities/Organization.ts [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+
+import BaseEntity from "../core/BaseEntity";
+import NumberValidator from "../core/validators/NumberValidator";
+import StringValidator from "../core/validators/StringValidator";
+import DateValidator from "../core/validators/DateValidator";
+import ValidationError from "../core/ValidationError";
+import User, {UserValidationMap} from "./User";
+
+export interface OrganizationValidationMap {
+    id?: boolean;
```
Comment (DanilAndreev) [inline src/entities/Organization.ts:23]: remove optional params. Make them required!

File: src/entities/User.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+    username?: boolean;
+    email?: boolean;
+    deleted?: boolean;
+    createdAt?: boolean;
+    updatedAt?: boolean;
+    bearer?: boolean;
+}
+
+export default class User extends BaseEntity {
+    public id?: number;
```
Comment (DanilAndreev) [inline src/entities/User.ts]: Make params required!

File: src/entities/UserToken.ts [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+export interface UserTokensValidationMap {
+    id?: boolean;
+    name?: boolean;
+    description?: boolean;
+    token?: boolean;
+    createdAt?: boolean;
+}
+
+export default class UserToken extends BaseEntity {
+    public id?: number;
```
Comment (DanilAndreev) [inline src/entities/UserToken.ts]: Params required

File: src/layout/MonitorLayout/MonitorLayout.tsx [hunk 4]
```diff
@@ -55,87 +70,221 @@ const MonitorLayout = React.forwardRef((props: MonitorLayoutProps, ref: Ref<any>
...
+
+    const handleDrawerOpen = () => {
+        setOpen(true);
+    };
+
+    const handleDrawerClose = () => {
+        setOpen(false);
+    };
+
+    const toggleDrawer = (anchor: Anchor, open: boolean) => (
```
Comment (DanilAndreev) [inline src/layout/MonitorLayout/MonitorLayout.tsx:74]: code style!

**Review by DanilAndreev — CHANGES_REQUESTED** [review]

**Review by DanilAndreev — APPROVED** [review]
