### PR TITLE
Fix small bugs

### LINKED ISSUE #128: Unrecognized error on login with incorrect credentials.
# Describe the bug 👀

When I am trying to log in with incorrect credentials I get ```UnrecognizedError```.

## How to reproduce 🏃:

1. Go to login page.
2. Fill fields with incorrect credentials. Incorrect means credentials of user, that does not exists.
3. Press sign in button.
4. Get ```UnrecognizedError```

## Expected behavior 🙌
I expected to get ___Incorrect username or password___ message. Or you can output more detailed info. For expected, if user does not exist - answer ___User does not exist___. When password is incorrect - ___Incorrect password___.

## Screenshots ✨

image

### Desktop 💻:
 - OS: Windows 10
 - Browser Chrome
 - Version latest

### LINKED ISSUE #151: Create links on User Page to check organization

### LINKED ISSUE #153: Fix bugs with routes

### PR DESCRIPTION
**Pull request by MykytaNesterov**
# Pull Request ☁️
## Overview ✨
Fixed minor bugs, reworked errors handling on authorization page, some work was done with routes changing 
## Changes 🔧

- __[AuthorizationPageView]__ (closes #128) _Now errors are explained more detailed._
- __[UserPageView, OrganizationPageView]__ (closes #153) _Fixed bugs with routes on edit user page, added routes for redirecting on users and organizations_

## Additional context 🌟
None

### CODE REVIEW

File: src/views/SignUpPage/SignUpPage.tsx [hunk 1]
```diff
@@ -93,6 +93,7 @@ const SignUpPage = React.forwardRef((props: SignUpPageProps, ref: Ref<any>) => {
                 changeRoute({page: `user/${user.id}`});
             })
             .catch(err => {
+                console.log("kuku");
```
Comment (DanilAndreev) [inline src/views/SignUpPage/SignUpPage.tsx]: ну куку

**Review by DanilAndreev — CHANGES_REQUESTED** [review]

**Review by DanilAndreev — APPROVED** [review]
