### PR TITLE
Provided auto logout if smth go wrong.

### LINKED ISSUE #120: Provide auto logout if no user

### PR DESCRIPTION
**Pull request by ZaykaNya**

### CODE REVIEW

File: src/hooks/useAuth.tsx [hunk 1]
```diff
@@ -7,7 +7,7 @@
  * All rights reserved.
  */
 
-import React from "react";
+import React, {useEffect} from "react";
```
Comment (DanilAndreev) [inline src/hooks/useAuth.tsx]: Remove unused imports

File: src/layout/ChooseLayout/ChooseLayout.tsx [hunk 2]
```diff
@@ -7,14 +7,15 @@
  * All rights reserved.
  */
 
-import React, {Ref} from 'react';
+import React, {Ref, useEffect, useState} from 'react';
```
Comment (DanilAndreev) [inline src/layout/ChooseLayout/ChooseLayout.tsx]: Unused import

**Review by DanilAndreev — CHANGES_REQUESTED** [review]

**Review by DanilAndreev — APPROVED** [review]
